/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapCategoriesDotxmlRouteImport } from './routes/sitemap-categories[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCatalogueRouteImport } from './routes/admin.catalogue'
import { Route as AdminBillsRouteImport } from './routes/admin.bills'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminProductsListRouteImport } from './routes/admin.products.list'
import { Route as AdminProductsAddRouteImport } from './routes/admin.products.add'
import { Route as AdminOrdersListRouteImport } from './routes/admin.orders.list'
import { Route as AdminOrdersCreateRouteImport } from './routes/admin.orders.create'
import { Route as AdminInventoryTakeOutRouteImport } from './routes/admin.inventory.take-out'
import { Route as AdminInventoryStockIntakeRouteImport } from './routes/admin.inventory.stock-intake'
import { Route as AdminInventoryReturnsRouteImport } from './routes/admin.inventory.returns'
import { Route as AdminInventoryRecordsRouteImport } from './routes/admin.inventory.records'
import { Route as AdminInventoryProductsRouteImport } from './routes/admin.inventory.products'
import { Route as AdminFinanceReportRouteImport } from './routes/admin.finance.report'
import { Route as AdminFinanceRecordsRouteImport } from './routes/admin.finance.records'
import { Route as AdminCategoriesSubCategoryRouteImport } from './routes/admin.categories.sub-category'
import { Route as AdminCategoriesCategoryRouteImport } from './routes/admin.categories.category'
import { Route as AdminCategoriesBrandsRouteImport } from './routes/admin.categories.brands'
import { Route as AdminCatalogueListRouteImport } from './routes/admin.catalogue.list'
import { Route as AdminCatalogueAddRouteImport } from './routes/admin.catalogue.add'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCategoriesDotxmlRoute = SitemapCategoriesDotxmlRouteImport.update({
  id: '/sitemap-categories.xml',
  path: '/sitemap-categories.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.products.lazy').then((d) => d.Route),
)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.orders.lazy').then((d) => d.Route))
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.inventory.lazy').then((d) => d.Route),
)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.categories.lazy').then((d) => d.Route),
)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsListRoute = AdminProductsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsAddRoute = AdminProductsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersListRoute = AdminOrdersListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersCreateRoute = AdminOrdersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminInventoryTakeOutRoute = AdminInventoryTakeOutRouteImport.update({
  id: '/take-out',
  path: '/take-out',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryStockIntakeRoute =
  AdminInventoryStockIntakeRouteImport.update({
    id: '/stock-intake',
    path: '/stock-intake',
    getParentRoute: () => AdminInventoryRoute,
  } as any)
const AdminInventoryReturnsRoute = AdminInventoryReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryRecordsRoute = AdminInventoryRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryProductsRoute = AdminInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminFinanceReportRoute = AdminFinanceReportRouteImport.update({
  id: '/finance/report',
  path: '/finance/report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRecordsRoute = AdminFinanceRecordsRouteImport.update({
  id: '/finance/records',
  path: '/finance/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesSubCategoryRoute =
  AdminCategoriesSubCategoryRouteImport.update({
    id: '/sub-category',
    path: '/sub-category',
    getParentRoute: () => AdminCategoriesRoute,
  } as any)
const AdminCategoriesCategoryRoute = AdminCategoriesCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminCategoriesBrandsRoute = AdminCategoriesBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminCatalogueListRoute = AdminCatalogueListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AdminCatalogueRoute,
} as any)
const AdminCatalogueAddRoute = AdminCatalogueAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminCatalogueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/catalogue': typeof AdminCatalogueRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalogue/add': typeof AdminCatalogueAddRoute
  '/admin/catalogue/list': typeof AdminCatalogueListRoute
  '/admin/categories/brands': typeof AdminCategoriesBrandsRoute
  '/admin/categories/category': typeof AdminCategoriesCategoryRoute
  '/admin/categories/sub-category': typeof AdminCategoriesSubCategoryRoute
  '/admin/finance/records': typeof AdminFinanceRecordsRoute
  '/admin/finance/report': typeof AdminFinanceReportRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/inventory/records': typeof AdminInventoryRecordsRoute
  '/admin/inventory/returns': typeof AdminInventoryReturnsRoute
  '/admin/inventory/stock-intake': typeof AdminInventoryStockIntakeRoute
  '/admin/inventory/take-out': typeof AdminInventoryTakeOutRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/orders/list': typeof AdminOrdersListRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products/list': typeof AdminProductsListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/catalogue': typeof AdminCatalogueRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/catalogue/add': typeof AdminCatalogueAddRoute
  '/admin/catalogue/list': typeof AdminCatalogueListRoute
  '/admin/categories/brands': typeof AdminCategoriesBrandsRoute
  '/admin/categories/category': typeof AdminCategoriesCategoryRoute
  '/admin/categories/sub-category': typeof AdminCategoriesSubCategoryRoute
  '/admin/finance/records': typeof AdminFinanceRecordsRoute
  '/admin/finance/report': typeof AdminFinanceReportRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/inventory/records': typeof AdminInventoryRecordsRoute
  '/admin/inventory/returns': typeof AdminInventoryReturnsRoute
  '/admin/inventory/stock-intake': typeof AdminInventoryStockIntakeRoute
  '/admin/inventory/take-out': typeof AdminInventoryTakeOutRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/orders/list': typeof AdminOrdersListRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products/list': typeof AdminProductsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/catalogue': typeof AdminCatalogueRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalogue/add': typeof AdminCatalogueAddRoute
  '/admin/catalogue/list': typeof AdminCatalogueListRoute
  '/admin/categories/brands': typeof AdminCategoriesBrandsRoute
  '/admin/categories/category': typeof AdminCategoriesCategoryRoute
  '/admin/categories/sub-category': typeof AdminCategoriesSubCategoryRoute
  '/admin/finance/records': typeof AdminFinanceRecordsRoute
  '/admin/finance/report': typeof AdminFinanceReportRoute
  '/admin/inventory/products': typeof AdminInventoryProductsRoute
  '/admin/inventory/records': typeof AdminInventoryRecordsRoute
  '/admin/inventory/returns': typeof AdminInventoryReturnsRoute
  '/admin/inventory/stock-intake': typeof AdminInventoryStockIntakeRoute
  '/admin/inventory/take-out': typeof AdminInventoryTakeOutRoute
  '/admin/orders/create': typeof AdminOrdersCreateRoute
  '/admin/orders/list': typeof AdminOrdersListRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products/list': typeof AdminProductsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/robots.txt'
    | '/shop'
    | '/sitemap-categories.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bills'
    | '/admin/catalogue'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/products/$slug'
    | '/admin/'
    | '/admin/catalogue/add'
    | '/admin/catalogue/list'
    | '/admin/categories/brands'
    | '/admin/categories/category'
    | '/admin/categories/sub-category'
    | '/admin/finance/records'
    | '/admin/finance/report'
    | '/admin/inventory/products'
    | '/admin/inventory/records'
    | '/admin/inventory/returns'
    | '/admin/inventory/stock-intake'
    | '/admin/inventory/take-out'
    | '/admin/orders/create'
    | '/admin/orders/list'
    | '/admin/products/add'
    | '/admin/products/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/robots.txt'
    | '/shop'
    | '/sitemap-categories.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bills'
    | '/admin/catalogue'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/products/$slug'
    | '/admin'
    | '/admin/catalogue/add'
    | '/admin/catalogue/list'
    | '/admin/categories/brands'
    | '/admin/categories/category'
    | '/admin/categories/sub-category'
    | '/admin/finance/records'
    | '/admin/finance/report'
    | '/admin/inventory/products'
    | '/admin/inventory/records'
    | '/admin/inventory/returns'
    | '/admin/inventory/stock-intake'
    | '/admin/inventory/take-out'
    | '/admin/orders/create'
    | '/admin/orders/list'
    | '/admin/products/add'
    | '/admin/products/list'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/robots.txt'
    | '/shop'
    | '/sitemap-categories.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/bills'
    | '/admin/catalogue'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/products/$slug'
    | '/admin/'
    | '/admin/catalogue/add'
    | '/admin/catalogue/list'
    | '/admin/categories/brands'
    | '/admin/categories/category'
    | '/admin/categories/sub-category'
    | '/admin/finance/records'
    | '/admin/finance/report'
    | '/admin/inventory/products'
    | '/admin/inventory/records'
    | '/admin/inventory/returns'
    | '/admin/inventory/stock-intake'
    | '/admin/inventory/take-out'
    | '/admin/orders/create'
    | '/admin/orders/list'
    | '/admin/products/add'
    | '/admin/products/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapCategoriesDotxmlRoute: typeof SitemapCategoriesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapProductsDotxmlRoute: typeof SitemapProductsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products.xml': {
      id: '/sitemap-products.xml'
      path: '/sitemap-products.xml'
      fullPath: '/sitemap-products.xml'
      preLoaderRoute: typeof SitemapProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-categories.xml': {
      id: '/sitemap-categories.xml'
      path: '/sitemap-categories.xml'
      fullPath: '/sitemap-categories.xml'
      preLoaderRoute: typeof SitemapCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bills': {
      id: '/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/list': {
      id: '/admin/products/list'
      path: '/list'
      fullPath: '/admin/products/list'
      preLoaderRoute: typeof AdminProductsListRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/add': {
      id: '/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProductsAddRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/list': {
      id: '/admin/orders/list'
      path: '/list'
      fullPath: '/admin/orders/list'
      preLoaderRoute: typeof AdminOrdersListRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/create': {
      id: '/admin/orders/create'
      path: '/create'
      fullPath: '/admin/orders/create'
      preLoaderRoute: typeof AdminOrdersCreateRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/inventory/take-out': {
      id: '/admin/inventory/take-out'
      path: '/take-out'
      fullPath: '/admin/inventory/take-out'
      preLoaderRoute: typeof AdminInventoryTakeOutRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/stock-intake': {
      id: '/admin/inventory/stock-intake'
      path: '/stock-intake'
      fullPath: '/admin/inventory/stock-intake'
      preLoaderRoute: typeof AdminInventoryStockIntakeRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/returns': {
      id: '/admin/inventory/returns'
      path: '/returns'
      fullPath: '/admin/inventory/returns'
      preLoaderRoute: typeof AdminInventoryReturnsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/records': {
      id: '/admin/inventory/records'
      path: '/records'
      fullPath: '/admin/inventory/records'
      preLoaderRoute: typeof AdminInventoryRecordsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/products': {
      id: '/admin/inventory/products'
      path: '/products'
      fullPath: '/admin/inventory/products'
      preLoaderRoute: typeof AdminInventoryProductsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/finance/report': {
      id: '/admin/finance/report'
      path: '/finance/report'
      fullPath: '/admin/finance/report'
      preLoaderRoute: typeof AdminFinanceReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/records': {
      id: '/admin/finance/records'
      path: '/finance/records'
      fullPath: '/admin/finance/records'
      preLoaderRoute: typeof AdminFinanceRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/sub-category': {
      id: '/admin/categories/sub-category'
      path: '/sub-category'
      fullPath: '/admin/categories/sub-category'
      preLoaderRoute: typeof AdminCategoriesSubCategoryRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/categories/category': {
      id: '/admin/categories/category'
      path: '/category'
      fullPath: '/admin/categories/category'
      preLoaderRoute: typeof AdminCategoriesCategoryRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/categories/brands': {
      id: '/admin/categories/brands'
      path: '/brands'
      fullPath: '/admin/categories/brands'
      preLoaderRoute: typeof AdminCategoriesBrandsRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/catalogue/list': {
      id: '/admin/catalogue/list'
      path: '/list'
      fullPath: '/admin/catalogue/list'
      preLoaderRoute: typeof AdminCatalogueListRouteImport
      parentRoute: typeof AdminCatalogueRoute
    }
    '/admin/catalogue/add': {
      id: '/admin/catalogue/add'
      path: '/add'
      fullPath: '/admin/catalogue/add'
      preLoaderRoute: typeof AdminCatalogueAddRouteImport
      parentRoute: typeof AdminCatalogueRoute
    }
  }
}

interface AdminCatalogueRouteChildren {
  AdminCatalogueAddRoute: typeof AdminCatalogueAddRoute
  AdminCatalogueListRoute: typeof AdminCatalogueListRoute
}

const AdminCatalogueRouteChildren: AdminCatalogueRouteChildren = {
  AdminCatalogueAddRoute: AdminCatalogueAddRoute,
  AdminCatalogueListRoute: AdminCatalogueListRoute,
}

const AdminCatalogueRouteWithChildren = AdminCatalogueRoute._addFileChildren(
  AdminCatalogueRouteChildren,
)

interface AdminCategoriesRouteChildren {
  AdminCategoriesBrandsRoute: typeof AdminCategoriesBrandsRoute
  AdminCategoriesCategoryRoute: typeof AdminCategoriesCategoryRoute
  AdminCategoriesSubCategoryRoute: typeof AdminCategoriesSubCategoryRoute
}

const AdminCategoriesRouteChildren: AdminCategoriesRouteChildren = {
  AdminCategoriesBrandsRoute: AdminCategoriesBrandsRoute,
  AdminCategoriesCategoryRoute: AdminCategoriesCategoryRoute,
  AdminCategoriesSubCategoryRoute: AdminCategoriesSubCategoryRoute,
}

const AdminCategoriesRouteWithChildren = AdminCategoriesRoute._addFileChildren(
  AdminCategoriesRouteChildren,
)

interface AdminInventoryRouteChildren {
  AdminInventoryProductsRoute: typeof AdminInventoryProductsRoute
  AdminInventoryRecordsRoute: typeof AdminInventoryRecordsRoute
  AdminInventoryReturnsRoute: typeof AdminInventoryReturnsRoute
  AdminInventoryStockIntakeRoute: typeof AdminInventoryStockIntakeRoute
  AdminInventoryTakeOutRoute: typeof AdminInventoryTakeOutRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryProductsRoute: AdminInventoryProductsRoute,
  AdminInventoryRecordsRoute: AdminInventoryRecordsRoute,
  AdminInventoryReturnsRoute: AdminInventoryReturnsRoute,
  AdminInventoryStockIntakeRoute: AdminInventoryStockIntakeRoute,
  AdminInventoryTakeOutRoute: AdminInventoryTakeOutRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersCreateRoute: typeof AdminOrdersCreateRoute
  AdminOrdersListRoute: typeof AdminOrdersListRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersCreateRoute: AdminOrdersCreateRoute,
  AdminOrdersListRoute: AdminOrdersListRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsAddRoute: typeof AdminProductsAddRoute
  AdminProductsListRoute: typeof AdminProductsListRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsAddRoute: AdminProductsAddRoute,
  AdminProductsListRoute: AdminProductsListRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillsRoute: typeof AdminBillsRoute
  AdminCatalogueRoute: typeof AdminCatalogueRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminResellersRoute: typeof AdminResellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinanceRecordsRoute: typeof AdminFinanceRecordsRoute
  AdminFinanceReportRoute: typeof AdminFinanceReportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillsRoute: AdminBillsRoute,
  AdminCatalogueRoute: AdminCatalogueRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminResellersRoute: AdminResellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinanceRecordsRoute: AdminFinanceRecordsRoute,
  AdminFinanceReportRoute: AdminFinanceReportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapCategoriesDotxmlRoute: SitemapCategoriesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
